/**
 * widget-catalog.ts — metadata-only registry.
 * IMPORTANT: This file must NOT import any React component files (.tsx widget files).
 * Importing it pulls in zero component code, enabling true code-splitting in WidgetRenderer.
 */
import type { WidgetMetadata } from './metadata';

// ─── Display ──────────────────────────────────────────────────────────────────

const TextWidgetMetadata: WidgetMetadata = {
  name: 'Text',
  icon: 'TextFields',
  category: 'display',
  description: 'Display static or dynamic text from entity states',
  defaultSize: { w: 200, h: 50 },
  minSize: { w: 50, h: 20 },
  requiresEntity: false,
  fields: [
    { name: 'x', type: 'number', label: 'X Position', default: 0, category: 'layout' },
    { name: 'y', type: 'number', label: 'Y Position', default: 0, category: 'layout' },
    { name: 'width', type: 'number', label: 'Width', default: 200, min: 50, category: 'layout' },
    { name: 'height', type: 'number', label: 'Height', default: 50, min: 20, category: 'layout' },
    { name: 'entity_id', type: 'entity', label: 'Entity ID', default: '', category: 'behavior', binding: true, description: 'Entity to display text from' },
    { name: 'text', type: 'text', label: 'Static Text', default: 'Text', category: 'behavior', binding: true, description: 'Static text (used when no entity selected)' },
    { name: 'prefix', type: 'text', label: 'Prefix', default: '', category: 'behavior', description: 'Text before value' },
    { name: 'unit', type: 'text', label: 'Unit Suffix', default: '', category: 'behavior', description: 'e.g. °C, %, W' },
    { name: 'textColor', type: 'color', label: 'Text Color', default: '#ffffff', category: 'style' },
    { name: 'fontFamily', type: 'font', label: 'Font Family', default: 'Arial, sans-serif', category: 'style' },
    { name: 'fontSize', type: 'number', label: 'Font Size', default: 16, min: 8, max: 72, category: 'style' },
    { name: 'fontWeight', type: 'select', label: 'Font Weight', default: 'normal', category: 'style', options: [
      { value: 'normal', label: 'Normal' }, { value: 'bold', label: 'Bold' },
      { value: '300', label: 'Light' }, { value: '500', label: 'Medium' },
    ]},
    { name: 'textAlign', type: 'select', label: 'Text Align', default: 'left', category: 'style', options: [
      { value: 'left', label: 'Left' }, { value: 'center', label: 'Center' }, { value: 'right', label: 'Right' },
    ]},
    { name: 'verticalAlign', type: 'select', label: 'Vertical Align', default: 'center', category: 'style', options: [
      { value: 'flex-start', label: 'Top' }, { value: 'center', label: 'Center' }, { value: 'flex-end', label: 'Bottom' },
    ]},
  ],
};

const GaugeWidgetMetadata: WidgetMetadata = {
  name: 'Gauge',
  icon: 'Speed',
  category: 'display',
  description: 'Circular gauge for displaying numeric sensor values',
  defaultSize: { w: 200, h: 200 },
  minSize: { w: 100, h: 100 },
  requiresEntity: true,
  fields: [
    { name: 'x', type: 'number', label: 'X Position', default: 0, category: 'layout' },
    { name: 'y', type: 'number', label: 'Y Position', default: 0, category: 'layout' },
    { name: 'width', type: 'number', label: 'Width', default: 200, min: 100, category: 'layout' },
    { name: 'height', type: 'number', label: 'Height', default: 200, min: 100, category: 'layout' },
    { name: 'entity_id', type: 'entity', label: 'Entity ID', default: '', category: 'behavior', description: 'Sensor entity to display' },
    { name: 'value', type: 'number', label: 'Override Value', default: 0, category: 'behavior', description: 'Direct value override (no entity)' },
    { name: 'min', type: 'number', label: 'Minimum Value', default: 0, category: 'behavior' },
    { name: 'max', type: 'number', label: 'Maximum Value', default: 100, category: 'behavior' },
    { name: 'unit', type: 'text', label: 'Unit', default: '', category: 'behavior', description: 'e.g. °C, %, W' },
    { name: 'gaugeType', type: 'select', label: 'Gauge Type', default: 'radial', category: 'style', options: [
      { value: 'radial', label: 'Radial (Semicircle)' }, { value: 'grafana', label: 'Grafana (3/4 Circle)' }, { value: 'semicircle', label: 'Semicircle' },
    ]},
    { name: 'needleOnly', type: 'checkbox', label: 'Needle Only Mode', default: false, category: 'style' },
    { name: 'needleStartAngle', type: 'number', label: 'Needle Start Angle (°)', default: -90, min: -180, max: 180, category: 'style', visibleWhen: { field: 'needleOnly', value: true } },
    { name: 'needleEndAngle', type: 'number', label: 'Needle End Angle (°)', default: 90, min: -180, max: 180, category: 'style', visibleWhen: { field: 'needleOnly', value: true } },
    { name: 'pointerType', type: 'select', label: 'Needle Type', default: 'needle', category: 'style', options: [
      { value: 'needle', label: 'Needle' }, { value: 'arrow', label: 'Arrow' }, { value: 'blob', label: 'Blob' },
    ]},
    { name: 'pointerColor', type: 'color', label: 'Needle Color', default: '#ffffff', category: 'style' },
    { name: 'pointerBaseColor', type: 'color', label: 'Center Dot Color', default: '', category: 'style' },
    { name: 'pointerLength', type: 'number', label: 'Needle Length', default: 0.7, min: 0.3, max: 1, step: 0.05, category: 'style' },
    { name: 'pointerWidth', type: 'number', label: 'Needle Width', default: 15, min: 5, max: 30, category: 'style' },
    { name: 'pointerElastic', type: 'checkbox', label: 'Elastic Animation', default: true, category: 'style' },
    { name: 'showArc', type: 'checkbox', label: 'Show Arc/Zones', default: true, category: 'style' },
    { name: 'arcWidth', type: 'number', label: 'Arc Width', default: 0.2, min: 0.05, max: 0.5, step: 0.05, category: 'style' },
    { name: 'zone1Color', type: 'color', label: 'Zone 1 Color', default: '#5BE12C', category: 'style' },
    { name: 'zone1Limit', type: 'number', label: 'Zone 1 Limit (%)', default: 33, min: 0, max: 100, category: 'style' },
    { name: 'zone2Color', type: 'color', label: 'Zone 2 Color', default: '#F5CD19', category: 'style' },
    { name: 'zone2Limit', type: 'number', label: 'Zone 2 Limit (%)', default: 66, min: 0, max: 100, category: 'style' },
    { name: 'zone3Color', type: 'color', label: 'Zone 3 Color', default: '#EA4228', category: 'style' },
    { name: 'showValue', type: 'checkbox', label: 'Show Value Label', default: true, category: 'style' },
    { name: 'showTicks', type: 'checkbox', label: 'Show Tick Labels', default: true, category: 'style' },
    { name: 'textColor', type: 'color', label: 'Text Color', default: '#ffffff', category: 'style' },
    { name: 'valueSize', type: 'number', label: 'Value Font Size', default: 24, min: 12, max: 48, category: 'style' },
  ],
};

const ProgressBarWidgetMetadata: WidgetMetadata = {
  name: 'Progress Bar',
  icon: 'LinearScaleOutlined',
  category: 'display',
  description: 'Linear progress indicator',
  defaultSize: { w: 300, h: 40 },
  minSize: { w: 100, h: 20 },
  requiresEntity: false,
  fields: [
    { name: 'x', type: 'number', label: 'X Position', default: 0, category: 'layout' },
    { name: 'y', type: 'number', label: 'Y Position', default: 0, category: 'layout' },
    { name: 'width', type: 'number', label: 'Width', default: 300, min: 100, category: 'layout' },
    { name: 'height', type: 'number', label: 'Height', default: 40, min: 20, category: 'layout' },
    { name: 'entity_id', type: 'entity', label: 'Entity ID', default: '', category: 'behavior' },
    { name: 'value', type: 'number', label: 'Value', default: 50, min: 0, max: 100, category: 'behavior', binding: true },
    { name: 'min', type: 'number', label: 'Min Value', default: 0, category: 'behavior' },
    { name: 'max', type: 'number', label: 'Max Value', default: 100, category: 'behavior' },
    { name: 'showValue', type: 'checkbox', label: 'Show Value', default: true, category: 'behavior' },
    { name: 'unit', type: 'text', label: 'Unit', default: '%', category: 'behavior' },
    { name: 'orientation', type: 'select', label: 'Orientation', default: 'horizontal', category: 'behavior', options: [
      { value: 'horizontal', label: 'Horizontal' }, { value: 'vertical', label: 'Vertical' },
    ]},
    { name: 'displayMode', type: 'select', label: 'Display Mode', default: 'standard', category: 'behavior', options: [
      { value: 'standard', label: 'Standard (Smooth)' }, { value: 'segmented', label: 'Segmented (Blocks)' },
      { value: 'graduated', label: 'Graduated (WiFi Style)' }, { value: 'striped', label: 'Striped (Animated)' },
    ]},
    { name: 'segmentCount', type: 'number', label: 'Segment Count', default: 10, min: 2, max: 50, category: 'behavior' },
    { name: 'segmentGap', type: 'number', label: 'Segment Gap', default: 4, min: 0, max: 20, category: 'behavior' },
    { name: 'emptySegmentMode', type: 'select', label: 'Empty Segments', default: 'outline', category: 'behavior', options: [
      { value: 'outline', label: 'Outline' }, { value: 'dimmed', label: 'Dimmed' }, { value: 'invisible', label: 'Invisible' },
    ]},
    { name: 'graduatedReverse', type: 'checkbox', label: 'Reverse Graduated', default: false, category: 'behavior' },
    { name: 'barColor', type: 'color', label: 'Bar Color', default: '#2196f3', category: 'style' },
    { name: 'backgroundColor', type: 'color', label: 'Background Color', default: '#424242', category: 'style' },
    { name: 'textColor', type: 'color', label: 'Text Color', default: '#ffffff', category: 'style' },
    { name: 'borderRadius', type: 'number', label: 'Border Radius', default: 0, category: 'style' },
    { name: 'useColorRanges', type: 'checkbox', label: 'Use Color Ranges', default: false, category: 'style' },
    { name: 'range1Min', type: 'number', label: 'Range 1 Min', default: 0, category: 'style' },
    { name: 'range1Max', type: 'number', label: 'Range 1 Max', default: 25, category: 'style' },
    { name: 'range1Color', type: 'color', label: 'Range 1 Color', default: '#f44336', category: 'style' },
    { name: 'range2Min', type: 'number', label: 'Range 2 Min', default: 26, category: 'style' },
    { name: 'range2Max', type: 'number', label: 'Range 2 Max', default: 50, category: 'style' },
    { name: 'range2Color', type: 'color', label: 'Range 2 Color', default: '#4caf50', category: 'style' },
    { name: 'range3Min', type: 'number', label: 'Range 3 Min', default: 51, category: 'style' },
    { name: 'range3Max', type: 'number', label: 'Range 3 Max', default: 75, category: 'style' },
    { name: 'range3Color', type: 'color', label: 'Range 3 Color', default: '#2196f3', category: 'style' },
    { name: 'range4Min', type: 'number', label: 'Range 4 Min', default: 76, category: 'style' },
    { name: 'range4Max', type: 'number', label: 'Range 4 Max', default: 100, category: 'style' },
    { name: 'range4Color', type: 'color', label: 'Range 4 Color', default: '#ffeb3b', category: 'style' },
  ],
};

const ProgressCircleWidgetMetadata: WidgetMetadata = {
  name: 'Progress Circle',
  icon: 'DonutLarge',
  category: 'display',
  description: 'Circular progress indicator',
  defaultSize: { w: 150, h: 150 },
  minSize: { w: 80, h: 80 },
  requiresEntity: false,
  fields: [
    { name: 'x', type: 'number', label: 'X Position', default: 0, category: 'layout' },
    { name: 'y', type: 'number', label: 'Y Position', default: 0, category: 'layout' },
    { name: 'width', type: 'number', label: 'Width', default: 150, min: 80, category: 'layout' },
    { name: 'height', type: 'number', label: 'Height', default: 150, min: 80, category: 'layout' },
    { name: 'entity_id', type: 'entity', label: 'Entity ID', default: '', category: 'behavior' },
    { name: 'value', type: 'number', label: 'Value', default: 50, min: 0, max: 100, category: 'behavior', binding: true },
    { name: 'min', type: 'number', label: 'Min Value', default: 0, category: 'behavior' },
    { name: 'max', type: 'number', label: 'Max Value', default: 100, category: 'behavior' },
    { name: 'showValue', type: 'checkbox', label: 'Show Value', default: true, category: 'behavior' },
    { name: 'unit', type: 'text', label: 'Unit', default: '%', category: 'behavior' },
    { name: 'counterClockwise', type: 'checkbox', label: 'Counter-Clockwise', default: false, category: 'behavior' },
    { name: 'segmented', type: 'checkbox', label: 'Segmented Mode', default: false, category: 'behavior' },
    { name: 'segmentCount', type: 'number', label: 'Segment Count', default: 36, min: 12, max: 72, category: 'behavior' },
    { name: 'segmentGap', type: 'number', label: 'Segment Gap', default: 2, min: 0, max: 10, category: 'behavior' },
    { name: 'strokeWidth', type: 'number', label: 'Stroke Width', default: 8, min: 1, max: 50, category: 'style' },
    { name: 'pathColor', type: 'color', label: 'Progress Color', default: '#2196f3', category: 'style' },
    { name: 'trailColor', type: 'color', label: 'Trail Color', default: '#d6d6d6', category: 'style' },
    { name: 'textColor', type: 'color', label: 'Text Color', default: '#000000', category: 'style' },
    { name: 'textSize', type: 'number', label: 'Text Size', default: 16, min: 8, max: 48, category: 'style' },
    { name: 'backgroundColor', type: 'color', label: 'Background Color', default: 'transparent', category: 'style' },
    { name: 'useColorRanges', type: 'checkbox', label: 'Use Color Ranges', default: false, category: 'style' },
    { name: 'range1Min', type: 'number', label: 'Range 1 Min', default: 0, category: 'style' },
    { name: 'range1Max', type: 'number', label: 'Range 1 Max', default: 25, category: 'style' },
    { name: 'range1Color', type: 'color', label: 'Range 1 Color', default: '#f44336', category: 'style' },
    { name: 'range2Min', type: 'number', label: 'Range 2 Min', default: 26, category: 'style' },
    { name: 'range2Max', type: 'number', label: 'Range 2 Max', default: 50, category: 'style' },
    { name: 'range2Color', type: 'color', label: 'Range 2 Color', default: '#4caf50', category: 'style' },
    { name: 'range3Min', type: 'number', label: 'Range 3 Min', default: 51, category: 'style' },
    { name: 'range3Max', type: 'number', label: 'Range 3 Max', default: 75, category: 'style' },
    { name: 'range3Color', type: 'color', label: 'Range 3 Color', default: '#2196f3', category: 'style' },
    { name: 'range4Min', type: 'number', label: 'Range 4 Min', default: 76, category: 'style' },
    { name: 'range4Max', type: 'number', label: 'Range 4 Max', default: 100, category: 'style' },
    { name: 'range4Color', type: 'color', label: 'Range 4 Color', default: '#ffeb3b', category: 'style' },
  ],
};

const ValueWidgetMetadata: WidgetMetadata = {
  name: 'Value',
  icon: 'Pin',
  category: 'display',
  description: 'Display formatted numeric values with prefix/suffix',
  defaultSize: { w: 150, h: 60 },
  minSize: { w: 50, h: 20 },
  requiresEntity: false,
  fields: [
    { name: 'x', type: 'number', label: 'X Position', default: 0, category: 'layout' },
    { name: 'y', type: 'number', label: 'Y Position', default: 0, category: 'layout' },
    { name: 'width', type: 'number', label: 'Width', default: 150, min: 50, category: 'layout' },
    { name: 'height', type: 'number', label: 'Height', default: 60, min: 20, category: 'layout' },
    { name: 'entity_id', type: 'entity', label: 'Entity ID', default: '', category: 'behavior', binding: true },
    { name: 'value', type: 'text', label: 'Static Value', default: '0', category: 'behavior', binding: true },
    { name: 'prefix', type: 'text', label: 'Prefix', default: '', category: 'behavior' },
    { name: 'suffix', type: 'text', label: 'Suffix', default: '', category: 'behavior', description: 'e.g. °C, %, W' },
    { name: 'decimals', type: 'number', label: 'Decimal Places', default: 1, min: 0, max: 10, category: 'behavior' },
    { name: 'formatThousands', type: 'checkbox', label: 'Thousands Separator', default: true, category: 'behavior' },
    { name: 'fontFamily', type: 'font', label: 'Font Family', default: 'Arial, sans-serif', category: 'style' },
    { name: 'fontSize', type: 'number', label: 'Font Size', default: 32, min: 8, max: 120, category: 'style' },
    { name: 'fontWeight', type: 'select', label: 'Font Weight', default: 'bold', category: 'style', options: [
      { value: 'normal', label: 'Normal' }, { value: 'bold', label: 'Bold' },
      { value: '300', label: 'Light' }, { value: '500', label: 'Medium' },
    ]},
    { name: 'textAlign', type: 'select', label: 'Text Align', default: 'center', category: 'style', options: [
      { value: 'left', label: 'Left' }, { value: 'center', label: 'Center' }, { value: 'right', label: 'Right' },
    ]},
    { name: 'textColor', type: 'color', label: 'Text Color', default: '#ffffff', category: 'style' },
    { name: 'backgroundColor', type: 'color', label: 'Background Color', default: 'transparent', category: 'style' },
  ],
};

const IconWidgetMetadata: WidgetMetadata = {
  name: 'Icon',
  icon: 'StarOutlined',
  category: 'display',
  description: 'Display icons with dynamic colors and advanced effects',
  defaultSize: { w: 80, h: 80 },
  minSize: { w: 40, h: 40 },
  requiresEntity: false,
  fields: [
    { name: 'x', type: 'number', label: 'X Position', default: 0, category: 'layout' },
    { name: 'y', type: 'number', label: 'Y Position', default: 0, category: 'layout' },
    { name: 'width', type: 'number', label: 'Width', default: 80, min: 40, category: 'layout' },
    { name: 'height', type: 'number', label: 'Height', default: 80, min: 40, category: 'layout' },
    { name: 'icon', type: 'icon', label: 'Icon', default: 'mdi:lightbulb', category: 'behavior', binding: true },
    { name: 'entity_id', type: 'entity', label: 'Entity ID', default: '', category: 'behavior', binding: true },
    { name: 'color', type: 'color', label: 'Color', default: '#ffffff', category: 'style', binding: true },
    { name: 'activeColor', type: 'color', label: 'Active Color', default: '#ffc107', category: 'style' },
    { name: 'size', type: 'number', label: 'Icon Size (%)', default: 100, min: 10, max: 200, category: 'style' },
    { name: 'outlineMode', type: 'select', label: 'Outline Mode', default: 'none', category: 'style', options: [
      { value: 'none', label: 'No Outline' }, { value: 'outline', label: 'Outline' }, { value: 'filled', label: 'Filled Outline' },
    ]},
    { name: 'strokeWidth', type: 'slider', label: 'Stroke Width (px)', default: 2, min: 0, max: 10, step: 0.1, category: 'style' },
    { name: 'glowWidth', type: 'number', label: 'Glow Width (px)', default: 0, min: 0, max: 30, category: 'style' },
    { name: 'glowColor', type: 'color', label: 'Glow Color', default: '', category: 'style' },
    { name: 'shadowEnabled', type: 'checkbox', label: 'Enable Shadow', default: false, category: 'style' },
    { name: 'shadowColor', type: 'color', label: 'Shadow Color', default: '#000000', category: 'style' },
    { name: 'shadowOffsetX', type: 'slider', label: 'Shadow Offset X', default: 2, min: -20, max: 20, step: 1, category: 'style' },
    { name: 'shadowOffsetY', type: 'slider', label: 'Shadow Offset Y', default: 2, min: -20, max: 20, step: 1, category: 'style' },
    { name: 'shadowBlur', type: 'slider', label: 'Shadow Blur', default: 4, min: 0, max: 30, step: 1, category: 'style' },
    { name: 'enableRotation', type: 'checkbox', label: 'Enable Rotation', default: false, category: 'style' },
    { name: 'rotationSpeed', type: 'slider', label: 'Rotation Speed (s)', default: 2, min: 0.5, max: 10, step: 0.5, category: 'style' },
    { name: 'fillDirection', type: 'select', label: 'Fill Direction', default: 'bottom-up', category: 'style', options: [
      { value: 'bottom-up', label: 'Bottom Up' }, { value: 'top-down', label: 'Top Down' },
      { value: 'left-to-right', label: 'Left to Right' }, { value: 'right-to-left', label: 'Right to Left' },
    ]},
    { name: 'fillColor', type: 'color', label: 'Fill Color', default: '#00ff00', category: 'style' },
    { name: 'fillImage', type: 'text', label: 'Fill Image URL', default: '', category: 'style' },
    { name: 'coverColor', type: 'color', label: 'Cover Color', default: '#000000', category: 'style' },
    { name: 'fillEntity', type: 'entity', label: 'Fill Entity', default: '', category: 'behavior', binding: true },
    { name: 'fillMin', type: 'number', label: 'Fill Min Value', default: 0, category: 'style' },
    { name: 'fillMax', type: 'number', label: 'Fill Max Value', default: 100, category: 'style' },
    { name: 'fillValue', type: 'number', label: 'Fill Value (%)', default: 0, min: 0, max: 100, category: 'behavior' },
  ],
};

const WeatherWidgetMetadata: WidgetMetadata = {
  name: 'Weather',
  icon: 'WbSunny',
  category: 'display',
  description: 'Display current weather conditions and forecast',
  defaultSize: { w: 320, h: 220 },
  requiresEntity: false,
  fields: [
    { name: 'width', type: 'number', label: 'Width', default: 320, min: 120, category: 'layout' },
    { name: 'height', type: 'number', label: 'Height', default: 220, min: 100, category: 'layout' },
    { name: 'entity_id', type: 'entity', label: 'Weather Entity', default: '', category: 'behavior' },
    { name: 'compactMode', type: 'checkbox', label: 'Compact Mode', default: false, category: 'behavior' },
    { name: 'showForecast', type: 'checkbox', label: 'Show Forecast', default: true, category: 'behavior' },
    { name: 'forecastDays', type: 'number', label: 'Forecast Days', default: 5, min: 2, max: 7, category: 'behavior' },
    { name: 'showHumidity', type: 'checkbox', label: 'Show Humidity', default: true, category: 'behavior' },
    { name: 'showWind', type: 'checkbox', label: 'Show Wind', default: true, category: 'behavior' },
    { name: 'showPressure', type: 'checkbox', label: 'Show Pressure', default: false, category: 'behavior' },
    { name: 'temperatureColor', type: 'color', label: 'Temperature Color', default: '#ffffff', category: 'style' },
    { name: 'conditionColor', type: 'color', label: 'Text Color', default: '#cccccc', category: 'style' },
  ],
};

const CalendarWidgetMetadata: WidgetMetadata = {
  name: 'Calendar',
  icon: 'CalendarMonth',
  category: 'display',
  description: 'Monthly calendar with today highlight and month navigation',
  defaultSize: { w: 320, h: 300 },
  minSize: { w: 200, h: 220 },
  requiresEntity: false,
  fields: [
    { name: 'width',       type: 'number',   label: 'Width',           default: 320, min: 200, category: 'layout' },
    { name: 'height',      type: 'number',   label: 'Height',          default: 300, min: 220, category: 'layout' },
    { name: 'accentColor', type: 'color',    label: 'Accent Color',    default: '#6c63ff', category: 'style' },
    { name: 'textColor',   type: 'color',    label: 'Text Color',      default: '#e0e0e0', category: 'style' },
    { name: 'bgColor',     type: 'color',    label: 'Background',      default: 'transparent', category: 'style' },
    { name: 'fontSize',    type: 'number',   label: 'Font Size',       default: 12, min: 8, max: 24, category: 'style' },
    { name: 'firstDay',    type: 'select',   label: 'First Day',       default: '0', category: 'behavior',
      options: [{ value: '0', label: 'Sunday' }, { value: '1', label: 'Monday' }] },
    { name: 'showNav',     type: 'checkbox', label: 'Show nav arrows', default: true, category: 'behavior' },
  ],
};

const GraphWidgetMetadata: WidgetMetadata = {
  name: 'Graph',
  icon: 'ShowChart',
  category: 'display',
  description: 'Display sensor history as line, bar, or area chart',
  defaultSize: { w: 400, h: 250 },
  requiresEntity: false,
  fields: [
    { name: 'width', type: 'number', label: 'Width', default: 400, min: 200, category: 'layout' },
    { name: 'height', type: 'number', label: 'Height', default: 250, min: 150, category: 'layout' },
    { name: 'entity_id', type: 'entity', label: 'Entity ID', default: '', category: 'behavior' },
    { name: 'chartType', type: 'select', label: 'Chart Type', default: 'line', category: 'behavior', options: [
      { value: 'line', label: 'Line' }, { value: 'bar', label: 'Bar' }, { value: 'area', label: 'Area' },
    ]},
    { name: 'dataPoints', type: 'number', label: 'Max Data Points', default: 50, min: 5, max: 200, category: 'behavior' },
    { name: 'smooth', type: 'checkbox', label: 'Smooth Lines', default: true, category: 'behavior' },
    { name: 'showLegend', type: 'checkbox', label: 'Show Legend', default: true, category: 'behavior' },
    { name: 'showGrid', type: 'checkbox', label: 'Show Grid', default: true, category: 'behavior' },
    { name: 'lineColor', type: 'color', label: 'Line/Bar Color', default: '#2196f3', category: 'style' },
    { name: 'backgroundColor', type: 'color', label: 'Background', default: 'transparent', category: 'style' },
    { name: 'textColor', type: 'color', label: 'Text Color', default: '#ffffff', category: 'style' },
  ],
};

const ScrollingTextWidgetMetadata: WidgetMetadata = {
  name: 'Scrolling Text',
  icon: 'TextRotationNone',
  category: 'display',
  description: 'Right-to-left scrolling ticker text',
  defaultSize: { w: 400, h: 60 },
  minSize: { w: 100, h: 30 },
  requiresEntity: false,
  fields: [
    { name: 'x', type: 'number', label: 'X Position', default: 0, category: 'layout' },
    { name: 'y', type: 'number', label: 'Y Position', default: 0, category: 'layout' },
    { name: 'width', type: 'number', label: 'Width', default: 400, min: 100, category: 'layout' },
    { name: 'height', type: 'number', label: 'Height', default: 60, min: 30, category: 'layout' },
    { name: 'text', type: 'text', label: 'Text', default: 'Scrolling text goes here...', category: 'behavior' },
    { name: 'entity_id', type: 'entity', label: 'Entity ID (optional)', default: '', category: 'behavior' },
    { name: 'scrollSpeed', type: 'number', label: 'Scroll Speed (px/s)', default: 50, min: 10, max: 200, category: 'behavior' },
    { name: 'pauseOnHover', type: 'checkbox', label: 'Pause on Hover', default: true, category: 'behavior' },
    { name: 'separator', type: 'text', label: 'Separator', default: '  •  ', category: 'behavior' },
    { name: 'textColor', type: 'color', label: 'Text Color', default: '#ffffff', category: 'style' },
    { name: 'backgroundColor', type: 'color', label: 'Background Color', default: 'transparent', category: 'style' },
    { name: 'fontSize', type: 'number', label: 'Font Size', default: 18, min: 10, max: 72, category: 'style' },
    { name: 'fontFamily', type: 'font', label: 'Font Family', default: 'Arial, sans-serif', category: 'style' },
    { name: 'fontWeight', type: 'select', label: 'Font Weight', default: 'normal', category: 'style', options: [
      { value: 'normal', label: 'Normal' }, { value: 'bold', label: 'Bold' },
      { value: '300', label: 'Light' }, { value: '500', label: 'Medium' },
    ]},
  ],
};

const HtmlWidgetMetadata: WidgetMetadata = {
  name: 'HTML',
  icon: 'CodeOutlined',
  category: 'display',
  description: 'Display custom HTML content',
  defaultSize: { w: 400, h: 300 },
  requiresEntity: false,
  fields: [
    { name: 'width', type: 'number', label: 'Width', default: 400, min: 100, category: 'layout' },
    { name: 'height', type: 'number', label: 'Height', default: 300, min: 100, category: 'layout' },
    { name: 'useEntityHtml', type: 'checkbox', label: 'Use Entity HTML', default: false, category: 'behavior' },
    { name: 'htmlEntity', type: 'entity', label: 'HTML Entity', default: '', category: 'behavior' },
    { name: 'htmlAttribute', type: 'text', label: 'HTML Attribute', default: '', category: 'behavior' },
    { name: 'html', type: 'textarea', label: 'HTML Content', default: '<div>Enter HTML here</div>', category: 'behavior' },
    { name: 'overflow', type: 'select', label: 'Overflow', default: 'auto', category: 'behavior', options: [
      { value: 'auto', label: 'Auto' }, { value: 'hidden', label: 'Hidden' },
      { value: 'scroll', label: 'Scroll' }, { value: 'visible', label: 'Visible' },
    ]},
    { name: 'backgroundColor', type: 'color', label: 'Background Color', default: 'transparent', category: 'style' },
    { name: 'padding', type: 'number', label: 'Padding', default: 8, min: 0, max: 50, category: 'style' },
  ],
};

const ResolutionWidgetMetadata: WidgetMetadata = {
  name: 'Resolution',
  icon: 'MonitorOutlined',
  category: 'display',
  description: 'Display viewport resolution and aspect ratio (developer tool)',
  defaultSize: { w: 200, h: 150 },
  requiresEntity: false,
  fields: [
    { name: 'width', type: 'number', label: 'Width', default: 200, min: 100, category: 'layout' },
    { name: 'height', type: 'number', label: 'Height', default: 150, min: 80, category: 'layout' },
    { name: 'showResolution', type: 'checkbox', label: 'Show Resolution', default: true, category: 'behavior' },
    { name: 'showRatio', type: 'checkbox', label: 'Show Aspect Ratio', default: true, category: 'behavior' },
    { name: 'showLabel', type: 'checkbox', label: 'Show Label', default: true, category: 'behavior' },
    { name: 'textColor', type: 'color', label: 'Text Color', default: '#ffffff', category: 'style' },
    { name: 'labelColor', type: 'color', label: 'Label Color', default: '#cccccc', category: 'style' },
    { name: 'backgroundColor', type: 'color', label: 'Background Color', default: 'rgba(0,0,0,0.5)', category: 'style' },
    { name: 'fontSize', type: 'number', label: 'Font Size', default: 24, min: 12, max: 72, category: 'style' },
    { name: 'labelSize', type: 'number', label: 'Label Size', default: 14, min: 10, max: 32, category: 'style' },
  ],
};

// ─── Clocks ───────────────────────────────────────────────────────────────────

const FlipClockWidgetMetadata: WidgetMetadata = {
  name: 'Flip Clock',
  icon: 'FlipClock',
  category: 'clocks',
  description: 'Mechanical-style flip clock with realistic animations',
  defaultSize: { w: 400, h: 240 },
  minSize: { w: 300, h: 180 },
  requiresEntity: false,
  fields: [
    { name: 'x', type: 'number', label: 'X Position', default: 0, category: 'layout' },
    { name: 'y', type: 'number', label: 'Y Position', default: 0, category: 'layout' },
    { name: 'width', type: 'number', label: 'Width', default: 400, min: 300, category: 'layout' },
    { name: 'height', type: 'number', label: 'Height', default: 240, min: 180, category: 'layout' },
    { name: 'format', type: 'select', label: 'Time Format', default: '12', category: 'behavior', options: [
      { value: '12', label: '12 Hour' }, { value: '24', label: '24 Hour' },
    ]},
    { name: 'showSeconds', type: 'checkbox', label: 'Show Seconds', default: true, category: 'behavior' },
    { name: 'bgColor', type: 'color', label: 'Background Color', default: 'rgb(38, 37, 41)', category: 'style' },
    { name: 'cardTopColor', type: 'color', label: 'Card Top Color', default: 'rgb(48, 49, 53)', category: 'style' },
    { name: 'cardBottomColor', type: 'color', label: 'Card Bottom Color', default: 'rgb(57, 58, 63)', category: 'style' },
    { name: 'textColor', type: 'color', label: 'Text Color', default: '#ffffff', category: 'style' },
    { name: 'fontFamily', type: 'font', label: 'Font Family', default: '"Saira Extra Condensed", sans-serif', category: 'style' },
    { name: 'fontSizeScale', type: 'slider', label: 'Font Size Scale (%)', default: 100, min: 50, max: 150, step: 5, category: 'style' },
    { name: 'showGears', type: 'checkbox', label: 'Show Gears', default: true, category: 'style' },
    { name: 'showBorders', type: 'checkbox', label: 'Show Card Borders', default: true, category: 'style' },
    { name: 'showContainerBorder', type: 'checkbox', label: 'Show Container Border', default: true, category: 'style' },
  ],
};

const DigitalClockWidgetMetadata: WidgetMetadata = {
  name: 'Digital Clock',
  icon: 'DigitalClock',
  category: 'clocks',
  description: 'LED-style digital clock with date display',
  defaultSize: { w: 300, h: 120 },
  minSize: { w: 200, h: 80 },
  requiresEntity: false,
  fields: [
    { name: 'x', type: 'number', label: 'X Position', default: 0, category: 'layout' },
    { name: 'y', type: 'number', label: 'Y Position', default: 0, category: 'layout' },
    { name: 'width', type: 'number', label: 'Width', default: 300, min: 200, category: 'layout' },
    { name: 'height', type: 'number', label: 'Height', default: 120, min: 80, category: 'layout' },
    { name: 'format', type: 'select', label: 'Time Format', default: '12', category: 'behavior', options: [
      { value: '12', label: '12 Hour' }, { value: '24', label: '24 Hour' },
    ]},
    { name: 'showSeconds', type: 'checkbox', label: 'Show Seconds', default: true, category: 'behavior' },
    { name: 'showDate', type: 'checkbox', label: 'Show Date', default: true, category: 'behavior' },
    { name: 'showDay', type: 'checkbox', label: 'Show Day of Week', default: true, category: 'behavior' },
    { name: 'backgroundColor', type: 'color', label: 'Background Color', default: '#1a1a1a', category: 'style' },
    { name: 'timeColor', type: 'color', label: 'Time Color', default: '#00ff00', category: 'style' },
    { name: 'dateColor', type: 'color', label: 'Date Color', default: '#00ff00', category: 'style' },
    { name: 'fontFamily', type: 'font', label: 'Time Font', default: '"DSEG7 Classic", monospace', category: 'style' },
    { name: 'fontFamilySecondary', type: 'font', label: 'AM/PM & Date Font', default: 'Arial, sans-serif', category: 'style' },
    { name: 'fontSize', type: 'number', label: 'Clock Font Size', default: 48, min: 10, max: 200, category: 'style' },
    { name: 'dateFontSize', type: 'number', label: 'Date Font Size (0=auto)', default: 0, min: 0, max: 120, category: 'style' },
    { name: 'dateGap', type: 'number', label: 'Date Gap (px)', default: 8, min: 0, max: 80, category: 'style' },
    { name: 'glow', type: 'checkbox', label: 'Glow Effect', default: true, category: 'style' },
    { name: 'blinkColon', type: 'checkbox', label: 'Blinking Colon', default: true, category: 'style' },
  ],
};

const AnalogClockWidgetMetadata: WidgetMetadata = {
  name: 'Analog Clock',
  icon: 'Schedule',
  category: 'clocks',
  description: 'Station-style analog clock with authentic swinging second hand',
  defaultSize: { w: 300, h: 300 },
  minSize: { w: 100, h: 100 },
  requiresEntity: false,
  fields: [
    { name: 'x', type: 'number', label: 'X Position', default: 0, category: 'layout' },
    { name: 'y', type: 'number', label: 'Y Position', default: 0, category: 'layout' },
    { name: 'width', type: 'number', label: 'Width', default: 300, min: 100, category: 'layout' },
    { name: 'height', type: 'number', label: 'Height', default: 300, min: 100, category: 'layout' },
    { name: 'secondHandBehavior', type: 'select', label: 'Second Hand', default: 'swinging', category: 'behavior', options: [
      { value: 'swinging', label: 'Swinging (station clock)' }, { value: 'stepping', label: 'Stepping' }, { value: 'sweeping', label: 'Sweeping' },
    ]},
    { name: 'minuteHandBehavior', type: 'select', label: 'Minute Hand', default: 'stepping', category: 'behavior', options: [
      { value: 'stepping', label: 'Stepping' }, { value: 'sweeping', label: 'Sweeping' },
    ]},
    { name: 'secondHandStopTime', type: 'slider', label: 'Pause Time (s)', default: 1.5, min: 0, max: 5, step: 0.1, category: 'behavior' },
    { name: 'dial', type: 'select', label: 'Dial Style', default: 'bauhaus', category: 'style', options: [
      { value: 'bauhaus', label: 'Bauhaus' }, { value: 'austria', label: 'Austria' }, { value: 'vienna', label: 'Vienna' },
      { value: 'points', label: 'Points' }, { value: 'din41091_1', label: 'DIN 41091.1' }, { value: 'din41091_3', label: 'DIN 41091.3' },
      { value: 'din41091_4', label: 'DIN 41091.4' }, { value: 'romannumerals', label: 'Roman Numerals' },
      { value: 'palmerstone', label: 'Palmerstone' }, { value: 'aubigny', label: 'Aubigny' },
      { value: 'wandelhalle', label: 'Wandelhalle' }, { value: 'none', label: 'None (image overlay)' },
    ]},
    { name: 'hourHand', type: 'select', label: 'Hour Hand', default: 'din41092_3', category: 'style', options: [
      { value: 'bauhaus', label: 'Bauhaus' }, { value: 'german', label: 'German' }, { value: 'siemens', label: 'Siemens' },
      { value: 'siemens2', label: 'Siemens 2' }, { value: 'din41092_3', label: 'DIN 41092.3' }, { value: 'bigbang', label: 'Big Bang' },
      { value: 'wandelhalle', label: 'Wandelhalle' }, { value: 'zurichenge', label: 'Zürich Enge' }, { value: 'ottensen', label: 'Ottensen' },
      { value: 'newyork', label: 'New York' }, { value: 'samurai', label: 'Samurai' }, { value: 'westminster', label: 'Westminster' },
      { value: 'aubigny', label: 'Aubigny' }, { value: 'vienna', label: 'Vienna' }, { value: 'palmerstone', label: 'Palmerstone' },
    ]},
    { name: 'minuteHand', type: 'select', label: 'Minute Hand', default: 'din41092_3', category: 'style', options: [
      { value: 'bauhaus', label: 'Bauhaus' }, { value: 'german', label: 'German' }, { value: 'siemens', label: 'Siemens' },
      { value: 'siemens2', label: 'Siemens 2' }, { value: 'din41092_3', label: 'DIN 41092.3' }, { value: 'bigbang', label: 'Big Bang' },
      { value: 'wandelhalle', label: 'Wandelhalle' }, { value: 'zurichenge', label: 'Zürich Enge' }, { value: 'ottensen', label: 'Ottensen' },
      { value: 'newyork', label: 'New York' }, { value: 'samurai', label: 'Samurai' }, { value: 'westminster', label: 'Westminster' },
      { value: 'aubigny', label: 'Aubigny' }, { value: 'vienna', label: 'Vienna' }, { value: 'palmerstone', label: 'Palmerstone' },
    ]},
    { name: 'secondHand', type: 'select', label: 'Second Hand', default: 'swiss', category: 'style', options: [
      { value: 'bar', label: 'Bar' }, { value: 'bauhaus', label: 'Bauhaus' }, { value: 'german', label: 'German' },
      { value: 'din41071_1', label: 'DIN 41071.1' }, { value: 'din41071_2', label: 'DIN 41071.2' }, { value: 'bigbang', label: 'Big Bang' },
      { value: 'wandelhalle', label: 'Wandelhalle' }, { value: 'samurai', label: 'Samurai' }, { value: 'swiss', label: 'Swiss' },
    ]},
    { name: 'axisCover', type: 'select', label: 'Axis Cover', default: 'circle', category: 'style', options: [
      { value: 'circle', label: 'Circle' }, { value: 'hexagon', label: 'Hexagon' }, { value: 'octagon', label: 'Octagon' }, { value: 'none', label: 'None' },
    ]},
    { name: 'backgroundColor', type: 'color', label: 'Background', default: 'transparent', category: 'style' },
    { name: 'dialColor', type: 'color', label: 'Dial', default: '#505050', category: 'style' },
    { name: 'hourHandColor', type: 'color', label: 'Hour Hand', default: '#212121', category: 'style' },
    { name: 'minuteHandColor', type: 'color', label: 'Minute Hand', default: '#212121', category: 'style' },
    { name: 'secondHandColor', type: 'color', label: 'Second Hand', default: '#d11e00', category: 'style' },
    { name: 'axisCoverColor', type: 'color', label: 'Axis Cover', default: '#d11e00', category: 'style' },
    { name: 'shadowOpacity', type: 'slider', label: 'Shadow Opacity', default: 0.5, min: 0, max: 1, step: 0.05, category: 'style' },
    { name: 'shadowOffsetX', type: 'slider', label: 'Shadow X', default: 3, min: -10, max: 10, step: 1, category: 'style' },
    { name: 'shadowOffsetY', type: 'slider', label: 'Shadow Y', default: 3, min: -10, max: 10, step: 1, category: 'style' },
    { name: 'shadowBlur', type: 'slider', label: 'Shadow Blur', default: 1, min: 0, max: 10, step: 0.5, category: 'style' },
    { name: 'axisCoverRadius', type: 'slider', label: 'Axis Cover Radius', default: 9, min: 2, max: 20, step: 1, category: 'style' },
  ],
};

// ─── Control ──────────────────────────────────────────────────────────────────

const ButtonWidgetMetadata: WidgetMetadata = {
  name: 'Button',
  icon: 'TouchApp',
  category: 'control',
  description: 'Clickable button that triggers Home Assistant services',
  defaultSize: { w: 200, h: 80 },
  minSize: { w: 60, h: 40 },
  requiresEntity: false,
  fields: [
    { name: 'x', type: 'number', label: 'X Position', default: 0, category: 'layout' },
    { name: 'y', type: 'number', label: 'Y Position', default: 0, category: 'layout' },
    { name: 'width', type: 'number', label: 'Width', default: 200, min: 60, category: 'layout' },
    { name: 'height', type: 'number', label: 'Height', default: 80, min: 40, category: 'layout' },
    { name: 'label', type: 'text', label: 'Button Text', default: 'Button', category: 'behavior' },
    { name: 'entity_id', type: 'entity', label: 'Entity ID', default: '', category: 'behavior' },
    { name: 'actionType', type: 'select', label: 'Action Type', default: 'auto', category: 'behavior', options: [
      { value: 'auto', label: 'Auto-detect from Entity' }, { value: 'toggle', label: 'Toggle' },
      { value: 'turn_on', label: 'Turn On' }, { value: 'turn_off', label: 'Turn Off' },
      { value: 'custom', label: 'Custom Service Call' }, { value: 'navigation', label: 'Navigate to View' },
      { value: 'url', label: 'Open URL' }, { value: 'load-iframe', label: 'Load in IFrame' },
      { value: 'execute-automation', label: 'Execute Automation' }, { value: 'mqtt', label: 'MQTT Publish' },
    ]},
    { name: 'value', type: 'text', label: 'Value', default: '', category: 'behavior' },
    { name: 'customDomain', type: 'text', label: 'Service Domain', default: '', category: 'behavior', visibleWhen: { field: 'actionType', value: 'custom' } },
    { name: 'customService', type: 'text', label: 'Service Name', default: '', category: 'behavior', visibleWhen: { field: 'actionType', value: 'custom' } },
    { name: 'serviceData', type: 'text', label: 'Service Data (JSON)', default: '{}', category: 'behavior', visibleWhen: { field: 'actionType', value: 'custom' } },
    { name: 'targetView', type: 'text', label: 'Target View', default: '', category: 'behavior', visibleWhen: { field: 'actionType', value: 'navigation' } },
    { name: 'url', type: 'text', label: 'URL', default: '', category: 'behavior', visibleWhen: { field: 'actionType', value: 'url' } },
    { name: 'urlTarget', type: 'select', label: 'URL Target', default: '_blank', category: 'behavior', options: [
      { value: '_blank', label: 'New Tab' }, { value: '_self', label: 'Same Tab' },
    ], visibleWhen: { field: 'actionType', value: 'url' } },
    { name: 'iframeWidgetId', type: 'widget', label: 'IFrame Widget', default: '', category: 'behavior', visibleWhen: { field: 'actionType', value: 'load-iframe' } },
    { name: 'iframeUrl', type: 'text', label: 'IFrame URL', default: '', category: 'behavior', visibleWhen: { field: 'actionType', value: 'load-iframe' } },
    { name: 'automationEntityId', type: 'entity', label: 'Automation', default: '', category: 'behavior', domains: ['automation'], visibleWhen: { field: 'actionType', value: 'execute-automation' } },
    { name: 'mqttTopic', type: 'text', label: 'MQTT Topic', default: '', category: 'behavior', visibleWhen: { field: 'actionType', value: 'mqtt' } },
    { name: 'mqttPayload', type: 'text', label: 'MQTT Payload', default: '', category: 'behavior', visibleWhen: { field: 'actionType', value: 'mqtt' } },
    { name: 'mqttQos', type: 'select', label: 'MQTT QoS', default: '0', category: 'behavior', options: [
      { value: '0', label: '0 - At most once' }, { value: '1', label: '1 - At least once' }, { value: '2', label: '2 - Exactly once' },
    ], visibleWhen: { field: 'actionType', value: 'mqtt' } },
    { name: 'mqttRetain', type: 'checkbox', label: 'MQTT Retain', default: false, category: 'behavior', visibleWhen: { field: 'actionType', value: 'mqtt' } },
    { name: 'confirmAction', type: 'checkbox', label: 'Require Confirmation', default: false, category: 'behavior' },
    { name: 'confirmMessage', type: 'text', label: 'Confirmation Message', default: 'Are you sure?', category: 'behavior' },
    { name: 'hapticFeedback', type: 'checkbox', label: 'Haptic Feedback', default: false, category: 'behavior' },
    { name: 'clickFeedback', type: 'select', label: 'Click Feedback', default: 'scale', category: 'behavior', options: [
      { value: 'none', label: 'None' }, { value: 'scale', label: 'Scale (zoom)' }, { value: 'highlight', label: 'Highlight' },
      { value: 'ripple', label: 'Ripple Effect' }, { value: 'shadow', label: 'Shadow Pulse' }, { value: 'color', label: 'Color Change' },
    ]},
    { name: 'feedbackDuration', type: 'number', label: 'Feedback Duration (ms)', default: 200, min: 50, max: 1000, category: 'behavior' },
    { name: 'feedbackIntensity', type: 'slider', label: 'Feedback Intensity', default: 1.0, min: 0.5, max: 2.0, step: 0.1, category: 'behavior' },
    { name: 'clickBackgroundColor', type: 'color', label: 'Click Background Color', default: '#1976d2', category: 'behavior', visibleWhen: { field: 'clickFeedback', value: 'color' } },
    { name: 'clickBorderColor', type: 'color', label: 'Click Border Color', default: '#ffffff', category: 'behavior', visibleWhen: { field: 'clickFeedback', value: 'color' } },
    { name: 'clickBorderWidth', type: 'number', label: 'Click Border Width', default: 2, min: 0, max: 10, category: 'behavior', visibleWhen: { field: 'clickFeedback', value: 'color' } },
    { name: 'showIcon', type: 'checkbox', label: 'Show Icon', default: false, category: 'style' },
    { name: 'icon', type: 'icon', label: 'Icon', default: 'mdi:lightbulb', category: 'style' },
    { name: 'iconPosition', type: 'select', label: 'Icon Position', default: 'left', category: 'style', options: [
      { value: 'left', label: 'Left' }, { value: 'right', label: 'Right' }, { value: 'top', label: 'Top' },
      { value: 'bottom', label: 'Bottom' }, { value: 'only', label: 'Icon Only' },
    ]},
    { name: 'iconSize', type: 'number', label: 'Icon Size', default: 24, min: 12, max: 96, category: 'style' },
    { name: 'iconSpacing', type: 'number', label: 'Icon Spacing', default: 8, min: 0, max: 32, category: 'style' },
    { name: 'iconColor', type: 'color', label: 'Icon Color', default: '', category: 'style' },
    { name: 'textColor', type: 'color', label: 'Text Color', default: '#ffffff', category: 'style' },
    { name: 'fontFamily', type: 'font', label: 'Font Family', default: 'Arial, sans-serif', category: 'style' },
    { name: 'fontSize', type: 'number', label: 'Font Size', default: 16, min: 8, max: 72, category: 'style' },
    { name: 'fontWeight', type: 'select', label: 'Font Weight', default: 'normal', category: 'style', options: [
      { value: 'normal', label: 'Normal' }, { value: 'bold', label: 'Bold' }, { value: '300', label: 'Light' }, { value: '500', label: 'Medium' },
    ]},
  ],
};

const SwitchWidgetMetadata: WidgetMetadata = {
  name: 'Switch',
  icon: 'ToggleOnOutlined',
  category: 'control',
  description: 'Toggle switch for binary entities',
  defaultSize: { w: 200, h: 60 },
  minSize: { w: 80, h: 40 },
  requiresEntity: false,
  fields: [
    { name: 'x', type: 'number', label: 'X Position', default: 0, category: 'layout' },
    { name: 'y', type: 'number', label: 'Y Position', default: 0, category: 'layout' },
    { name: 'width', type: 'number', label: 'Width', default: 200, min: 80, category: 'layout' },
    { name: 'height', type: 'number', label: 'Height', default: 60, min: 40, category: 'layout' },
    { name: 'label', type: 'text', label: 'Label', default: 'Switch', category: 'behavior' },
    { name: 'labelPosition', type: 'select', label: 'Label Position', default: 'left', category: 'behavior', options: [
      { value: 'left', label: 'Left' }, { value: 'right', label: 'Right' }, { value: 'top', label: 'Top' }, { value: 'bottom', label: 'Bottom' },
    ]},
    { name: 'service_domain', type: 'text', label: 'Service Domain', default: 'homeassistant', category: 'behavior' },
    { name: 'entity_id', type: 'entity', label: 'Entity ID', default: '', category: 'behavior' },
    { name: 'state', type: 'text', label: 'State', default: 'off', category: 'behavior' },
    { name: 'onColor', type: 'color', label: 'On Color', default: '#4caf50', category: 'style' },
    { name: 'offColor', type: 'color', label: 'Off Color', default: '#757575', category: 'style' },
    { name: 'textColor', type: 'color', label: 'Text Color', default: '#ffffff', category: 'style' },
    { name: 'fontFamily', type: 'font', label: 'Font Family', default: 'Arial, sans-serif', category: 'style' },
    { name: 'fontSize', type: 'number', label: 'Font Size', default: 14, min: 8, max: 32, category: 'style' },
    { name: 'fontWeight', type: 'select', label: 'Font Weight', default: '500', category: 'style', options: [
      { value: '300', label: 'Light' }, { value: '400', label: 'Normal' }, { value: '500', label: 'Medium' },
      { value: '600', label: 'Semi-Bold' }, { value: '700', label: 'Bold' },
    ]},
    { name: 'thumbColor', type: 'color', label: 'Thumb Color', default: '#ffffff', category: 'style' },
  ],
};

const SliderWidgetMetadata: WidgetMetadata = {
  name: 'Slider',
  icon: 'TuneOutlined',
  category: 'control',
  description: 'Interactive slider for controlling entity values',
  defaultSize: { w: 300, h: 60 },
  minSize: { w: 100, h: 40 },
  requiresEntity: false,
  fields: [
    { name: 'x', type: 'number', label: 'X Position', default: 0, category: 'layout' },
    { name: 'y', type: 'number', label: 'Y Position', default: 0, category: 'layout' },
    { name: 'width', type: 'number', label: 'Width', default: 300, min: 100, category: 'layout' },
    { name: 'height', type: 'number', label: 'Height', default: 60, min: 40, category: 'layout' },
    { name: 'label', type: 'text', label: 'Label', default: 'Slider', category: 'behavior' },
    { name: 'entity_id', type: 'entity', label: 'Entity ID', default: '', category: 'behavior' },
    { name: 'min', type: 'number', label: 'Minimum Value', default: 0, category: 'behavior' },
    { name: 'max', type: 'number', label: 'Maximum Value', default: 100, category: 'behavior' },
    { name: 'step', type: 'number', label: 'Step', default: 1, category: 'behavior' },
    { name: 'value', type: 'number', label: 'Initial Value', default: 50, category: 'behavior' },
    { name: 'showValue', type: 'checkbox', label: 'Show Value', default: true, category: 'behavior' },
    { name: 'orientation', type: 'select', label: 'Orientation', default: 'horizontal', category: 'behavior', options: [
      { value: 'horizontal', label: 'Horizontal' }, { value: 'vertical', label: 'Vertical' },
    ]},
    { name: 'trackColor', type: 'color', label: 'Track Color', default: '#424242', category: 'style' },
    { name: 'fillColor', type: 'color', label: 'Fill Color', default: '#2196f3', category: 'style' },
    { name: 'thumbColor', type: 'color', label: 'Thumb Color', default: '#2196f3', category: 'style' },
    { name: 'thumbIcon', type: 'icon', label: 'Thumb Icon', default: '', category: 'style' },
    { name: 'thumbIconSize', type: 'number', label: 'Thumb Icon Size', default: 20, min: 12, max: 48, category: 'style' },
    { name: 'thumbIconOffsetX', type: 'number', label: 'Icon Offset X (%)', default: -50, min: -200, max: 200, category: 'style' },
    { name: 'thumbIconOffsetY', type: 'number', label: 'Icon Offset Y (%)', default: -50, min: -200, max: 200, category: 'style' },
    { name: 'textColor', type: 'color', label: 'Text Color', default: '#ffffff', category: 'style' },
    { name: 'fontSize', type: 'number', label: 'Font Size', default: 14, min: 8, max: 32, category: 'style' },
  ],
};

const KnobWidgetMetadata: WidgetMetadata = {
  name: 'Knob',
  icon: 'DialpadOutlined',
  category: 'control',
  description: 'Custom SVG rotary control with full marker customization',
  defaultSize: { w: 150, h: 150 },
  minSize: { w: 80, h: 80 },
  requiresEntity: false,
  fields: [
    { name: 'x', type: 'number', label: 'X Position', default: 0, category: 'layout' },
    { name: 'y', type: 'number', label: 'Y Position', default: 0, category: 'layout' },
    { name: 'width', type: 'number', label: 'Width', default: 150, min: 80, category: 'layout' },
    { name: 'height', type: 'number', label: 'Height', default: 150, min: 80, category: 'layout' },
    { name: 'label', type: 'text', label: 'Label', default: 'Knob', category: 'behavior' },
    { name: 'entity_id', type: 'entity', label: 'Entity ID', default: '', category: 'behavior' },
    { name: 'min', type: 'number', label: 'Minimum Value', default: 0, category: 'behavior' },
    { name: 'max', type: 'number', label: 'Maximum Value', default: 100, category: 'behavior' },
    { name: 'step', type: 'number', label: 'Step', default: 1, category: 'behavior' },
    { name: 'dialStep', type: 'number', label: 'Dial Step', default: 10, category: 'behavior' },
    { name: 'value', type: 'number', label: 'Initial Value', default: 50, category: 'behavior' },
    { name: 'showValue', type: 'select', label: 'Show Value', default: 'true', category: 'behavior', options: [
      { value: 'true', label: 'Show' }, { value: 'false', label: 'Hide' },
    ]},
    { name: 'valuePrefix', type: 'text', label: 'Value Prefix', default: '', category: 'behavior' },
    { name: 'valueSuffix', type: 'text', label: 'Value Suffix', default: '', category: 'behavior' },
    { name: 'angleOffset', type: 'number', label: 'Angle Offset (°)', default: 220, min: 0, max: 360, category: 'behavior' },
    { name: 'angleRange', type: 'number', label: 'Angle Range (°)', default: 280, min: 0, max: 360, category: 'behavior' },
    { name: 'skin', type: 'select', label: 'Knob Style', default: 'p1', category: 'style', options: [
      { value: 'p1', label: 'P1 - Circle with Dial' }, { value: 'p2', label: 'P2 - Arc with Pointer' },
      { value: 'p3', label: 'P3 - Arc Only' }, { value: 'p4', label: 'P4 - Circle with Ticks' }, { value: 'p5', label: 'P5 - Arc Pointer' },
    ]},
    { name: 'contentScale', type: 'number', label: 'Content Scale (%)', default: 100, min: 20, max: 150, category: 'style' },
    { name: 'knobColor', type: 'color', label: 'Knob Color', default: '#2196f3', category: 'style' },
    { name: 'textColor', type: 'color', label: 'Text Color', default: '#ffffff', category: 'style' },
    { name: 'accentColor', type: 'color', label: 'Accent Color', default: '#1976d2', category: 'style' },
    { name: 'scalePadding', type: 'number', label: 'Scale Padding (%)', default: 8, min: 0, max: 30, category: 'style' },
    { name: 'markerType', type: 'select', label: 'Marker Type', default: 'triangle', category: 'style', options: [
      { value: 'triangle', label: 'Triangle' }, { value: 'rect', label: 'Rectangle Block' },
      { value: 'dot', label: 'Dot (Circle)' }, { value: 'none', label: 'None' },
    ]},
    { name: 'markerWidth', type: 'number', label: 'Marker Size', default: 12, min: 4, max: 50, category: 'style' },
    { name: 'markerColor', type: 'color', label: 'Marker Color', default: '#ffeb3b', category: 'style' },
  ],
};

const InputTextWidgetMetadata: WidgetMetadata = {
  name: 'Input Text',
  icon: 'TextFields',
  category: 'control',
  description: 'Text input field bound to an input_text entity',
  defaultSize: { w: 250, h: 50 },
  requiresEntity: false,
  fields: [
    { name: 'width', type: 'number', label: 'Width', default: 250, min: 100, category: 'layout' },
    { name: 'height', type: 'number', label: 'Height', default: 50, min: 40, category: 'layout' },
    { name: 'entity_id', type: 'entity', label: 'Entity ID', default: '', category: 'behavior' },
    { name: 'placeholder', type: 'text', label: 'Placeholder', default: 'Enter text...', category: 'behavior' },
    { name: 'label', type: 'text', label: 'Label', default: '', category: 'behavior' },
    { name: 'passwordMode', type: 'checkbox', label: 'Password Mode', default: false, category: 'behavior' },
    { name: 'textColor', type: 'color', label: 'Text Color', default: '#ffffff', category: 'style' },
    { name: 'backgroundColor', type: 'color', label: 'Background Color', default: '#424242', category: 'style' },
    { name: 'borderColor', type: 'color', label: 'Border Color', default: '#666666', category: 'style' },
    { name: 'fontSize', type: 'number', label: 'Font Size', default: 14, min: 10, max: 32, category: 'style' },
  ],
};

const RadioButtonWidgetMetadata: WidgetMetadata = {
  name: 'Radio Button',
  icon: 'RadioButtonChecked',
  category: 'control',
  description: 'Single selection from multiple options',
  defaultSize: { w: 200, h: 150 },
  requiresEntity: false,
  fields: [
    { name: 'width', type: 'number', label: 'Width', default: 200, min: 100, category: 'layout' },
    { name: 'height', type: 'number', label: 'Height', default: 150, min: 80, category: 'layout' },
    { name: 'entity_id', type: 'entity', label: 'Entity ID', default: '', category: 'behavior' },
    { name: 'options', type: 'text', label: 'Options (comma-separated)', default: 'Option 1,Option 2,Option 3', category: 'behavior' },
    { name: 'values', type: 'text', label: 'Values (comma-separated)', default: '', category: 'behavior' },
    { name: 'orientation', type: 'select', label: 'Orientation', default: 'vertical', category: 'behavior', options: [
      { value: 'vertical', label: 'Vertical' }, { value: 'horizontal', label: 'Horizontal' },
    ]},
    { name: 'fontSize', type: 'number', label: 'Font Size', default: 14, min: 8, max: 24, category: 'style' },
    { name: 'textColor', type: 'color', label: 'Text Color', default: '#ffffff', category: 'style' },
    { name: 'activeColor', type: 'color', label: 'Active Color', default: '#2196f3', category: 'style' },
    { name: 'backgroundColor', type: 'color', label: 'Background Color', default: 'transparent', category: 'style' },
  ],
};

const ColorPickerWidgetMetadata: WidgetMetadata = {
  name: 'Color Picker',
  icon: 'Palette',
  category: 'control',
  description: 'Touch-friendly color picker — sends RGB to lights, hex to input_text',
  defaultSize: { w: 80, h: 80 },
  requiresEntity: false,
  fields: [
    { name: 'width', type: 'number', label: 'Width', default: 80, min: 40, category: 'layout' },
    { name: 'height', type: 'number', label: 'Height', default: 80, min: 40, category: 'layout' },
    { name: 'entity_id', type: 'entity', label: 'Entity', default: '', category: 'behavior' },
    { name: 'swatchWidth', type: 'number', label: 'Swatch Width', default: 60, min: 20, max: 200, category: 'style' },
    { name: 'swatchHeight', type: 'number', label: 'Swatch Height', default: 60, min: 20, max: 200, category: 'style' },
    { name: 'swatchBorderRadius', type: 'number', label: 'Swatch Radius', default: 4, min: 0, max: 50, category: 'style' },
  ],
};

// ─── Media ────────────────────────────────────────────────────────────────────

const ImageWidgetMetadata: WidgetMetadata = {
  name: 'Image',
  icon: 'ImageOutlined',
  category: 'media',
  description: 'Display images from URLs or entity pictures',
  defaultSize: { w: 300, h: 200 },
  minSize: { w: 100, h: 100 },
  requiresEntity: false,
  fields: [
    { name: 'x', type: 'number', label: 'X Position', default: 0, category: 'layout' },
    { name: 'y', type: 'number', label: 'Y Position', default: 0, category: 'layout' },
    { name: 'width', type: 'number', label: 'Width', default: 300, min: 100, category: 'layout' },
    { name: 'height', type: 'number', label: 'Height', default: 200, min: 100, category: 'layout' },
    { name: 'entity_id', type: 'entity', label: 'Camera Entity', default: '', category: 'behavior' },
    { name: 'localImagePath', type: 'file', label: 'Local Image Path', default: '', category: 'behavior' },
    { name: 'imageUrl', type: 'text', label: 'External URL', default: '', category: 'behavior' },
    { name: 'altText', type: 'text', label: 'Alt Text', default: 'Image', category: 'behavior' },
    { name: 'refreshInterval', type: 'number', label: 'Refresh Interval (ms)', default: 0, category: 'behavior', description: '0 = no auto-refresh' },
    { name: 'objectFit', type: 'select', label: 'Object Fit', default: 'cover', category: 'style', options: [
      { value: 'contain', label: 'Contain' }, { value: 'cover', label: 'Cover' },
      { value: 'fill', label: 'Fill' }, { value: 'none', label: 'None' }, { value: 'scale-down', label: 'Scale Down' },
    ]},
  ],
};

const CameraWidgetMetadata: WidgetMetadata = {
  name: 'Camera',
  icon: 'Videocam',
  category: 'media',
  description: 'Display a live snapshot from an HA camera entity',
  defaultSize: { w: 320, h: 240 },
  minSize: { w: 160, h: 120 },
  requiresEntity: true,
  fields: [
    { name: 'width', type: 'number', label: 'Width', default: 320, min: 160, category: 'layout' },
    { name: 'height', type: 'number', label: 'Height', default: 240, min: 120, category: 'layout' },
    { name: 'entity_id', type: 'entity', label: 'Camera Entity', default: '', category: 'behavior', domains: ['camera'] },
    { name: 'refreshInterval', type: 'number', label: 'Refresh Interval (ms)', default: 2000, min: 500, max: 60000, step: 500, category: 'behavior' },
    { name: 'showOverlay', type: 'checkbox', label: 'Show Entity Name Overlay', default: false, category: 'behavior' },
    { name: 'objectFit', type: 'select', label: 'Object Fit', default: 'cover', category: 'style', options: [
      { value: 'contain', label: 'Contain' }, { value: 'cover', label: 'Cover' }, { value: 'fill', label: 'Fill' },
    ]},
    { name: 'overlayBackground', type: 'color', label: 'Overlay Background', default: 'rgba(0,0,0,0.5)', category: 'style', visibleWhen: { field: 'showOverlay', value: true } },
    { name: 'overlayColor', type: 'color', label: 'Overlay Text Color', default: '#ffffff', category: 'style', visibleWhen: { field: 'showOverlay', value: true } },
  ],
};

// ─── Layout ───────────────────────────────────────────────────────────────────

const IFrameWidgetMetadata: WidgetMetadata = {
  name: 'IFrame',
  icon: 'Web',
  category: 'layout',
  description: 'Embed external websites or internal views',
  defaultSize: { w: 400, h: 300 },
  minSize: { w: 100, h: 100 },
  requiresEntity: false,
  fields: [
    { name: 'x', type: 'number', label: 'X Position', default: 0, category: 'layout' },
    { name: 'y', type: 'number', label: 'Y Position', default: 0, category: 'layout' },
    { name: 'width', type: 'number', label: 'Width', default: 400, min: 100, category: 'layout' },
    { name: 'height', type: 'number', label: 'Height', default: 300, min: 100, category: 'layout' },
    { name: 'urlType', type: 'select', label: 'URL Type', default: 'external', category: 'behavior', options: [
      { value: 'external', label: 'External URL' }, { value: 'view', label: 'Embed View' }, { value: 'entity', label: 'Entity State URL' },
    ]},
    { name: 'url', type: 'text', label: 'URL', default: '', category: 'behavior' },
    { name: 'viewId', type: 'text', label: 'View Name', default: '', category: 'behavior' },
    { name: 'entity_id', type: 'entity', label: 'URL Entity', default: '', category: 'behavior' },
    { name: 'allowFullscreen', type: 'checkbox', label: 'Allow Fullscreen', default: true, category: 'behavior' },
    { name: 'sandbox', type: 'text', label: 'Sandbox', default: '', category: 'behavior' },
    { name: 'scrolling', type: 'select', label: 'Scrollbars', default: 'auto', category: 'behavior', options: [
      { value: 'auto', label: 'Auto' }, { value: 'yes', label: 'Always Show' }, { value: 'no', label: 'Hide' },
    ]},
  ],
};

const BorderWidgetMetadata: WidgetMetadata = {
  name: 'Border',
  icon: 'BorderOuter',
  category: 'layout',
  description: 'Decorative border or frame',
  defaultSize: { w: 200, h: 200 },
  minSize: { w: 50, h: 50 },
  requiresEntity: false,
  fields: [
    { name: 'x', type: 'number', label: 'X Position', default: 0, category: 'layout' },
    { name: 'y', type: 'number', label: 'Y Position', default: 0, category: 'layout' },
    { name: 'width', type: 'number', label: 'Width', default: 200, min: 50, category: 'layout' },
    { name: 'height', type: 'number', label: 'Height', default: 200, min: 50, category: 'layout' },
  ],
};

const ShapeWidgetMetadata: WidgetMetadata = {
  name: 'Shape',
  icon: 'HexagonOutlined',
  category: 'layout',
  description: 'Custom polygon shape — sharp, rounded, or chamfered corners',
  defaultSize: { w: 200, h: 200 },
  minSize: { w: 30, h: 30 },
  requiresEntity: false,
  fields: [
    { name: 'x', type: 'number', label: 'X Position', default: 0, category: 'layout' },
    { name: 'y', type: 'number', label: 'Y Position', default: 0, category: 'layout' },
    { name: 'width', type: 'number', label: 'Width', default: 200, min: 30, category: 'layout' },
    { name: 'height', type: 'number', label: 'Height', default: 200, min: 30, category: 'layout' },
  ],
};

// ─── Registry ─────────────────────────────────────────────────────────────────

export const WIDGET_CATALOG: Record<string, WidgetMetadata> = {
  // Display
  text: TextWidgetMetadata,
  value: ValueWidgetMetadata,
  gauge: GaugeWidgetMetadata,
  progressbar: ProgressBarWidgetMetadata,
  progresscircle: ProgressCircleWidgetMetadata,
  icon: IconWidgetMetadata,
  html: HtmlWidgetMetadata,
  scrollingtext: ScrollingTextWidgetMetadata,
  weather: WeatherWidgetMetadata,
  calendar: CalendarWidgetMetadata,
  graph: GraphWidgetMetadata,
  resolution: ResolutionWidgetMetadata,
  // Clocks
  analogclock: AnalogClockWidgetMetadata,
  flipclock: FlipClockWidgetMetadata,
  digitalclock: DigitalClockWidgetMetadata,
  // Control
  button: ButtonWidgetMetadata,
  switch: SwitchWidgetMetadata,
  slider: SliderWidgetMetadata,
  knob: KnobWidgetMetadata,
  inputtext: InputTextWidgetMetadata,
  radiobutton: RadioButtonWidgetMetadata,
  colorpicker: ColorPickerWidgetMetadata,
  // Media
  image: ImageWidgetMetadata,
  camera: CameraWidgetMetadata,
  // Layout
  iframe: IFrameWidgetMetadata,
  border: BorderWidgetMetadata,
  shape: ShapeWidgetMetadata,
};

// ─── Additional Widgets ──────────────────────────────────────────────────────

const ScrollableContainerWidgetMetadata: WidgetMetadata = {
  name: 'Scrollable Container',
  icon: 'TableChartOutlined',
  category: 'layout',
  description: 'A scrollable styled container panel. Place other widgets on top using normal canvas positioning.',
  defaultSize: { w: 500, h: 400 },
  minSize: { w: 100, h: 100 },
  requiresEntity: false,
  fields: [
    { name: 'width', type: 'number', label: 'Width', default: 500, min: 100, category: 'layout' },
    { name: 'height', type: 'number', label: 'Height', default: 400, min: 100, category: 'layout' },
    { name: 'label', type: 'text', label: 'Label', default: '', category: 'behavior' },
    { name: 'scrollDirection', type: 'select', label: 'Scroll Direction', default: 'vertical', category: 'behavior', options: [
      { value: 'vertical', label: 'Vertical' },
      { value: 'horizontal', label: 'Horizontal' },
      { value: 'both', label: 'Both' },
      { value: 'none', label: 'None' },
    ]},
    { name: 'showScrollbar', type: 'checkbox', label: 'Show Scrollbar', default: true, category: 'behavior' },
    { name: 'backgroundColor', type: 'color', label: 'Background Color', default: 'rgba(255,255,255,0.05)', category: 'style' },
    { name: 'borderColor', type: 'color', label: 'Border Color', default: 'rgba(255,255,255,0.1)', category: 'style' },
    { name: 'borderWidth', type: 'number', label: 'Border Width', default: 1, min: 0, max: 10, category: 'style' },
    { name: 'borderRadius', type: 'number', label: 'Border Radius', default: 8, min: 0, max: 50, category: 'style' },
    { name: 'padding', type: 'number', label: 'Padding', default: 8, min: 0, max: 80, category: 'style' },
    { name: 'labelColor', type: 'color', label: 'Label Color', default: '#888888', category: 'style' },
    { name: 'labelSize', type: 'number', label: 'Label Font Size', default: 12, min: 8, max: 32, category: 'style' },
  ],
};

const KeyboardWidgetMetadata: WidgetMetadata = {
  name: 'Keyboard',
  icon: 'KeyboardOutlined',
  category: 'control',
  description: 'On-screen virtual keyboard for text input. Syncs with focused inputs and/or an input_text entity.',
  defaultSize: { w: 700, h: 260 },
  minSize: { w: 400, h: 180 },
  requiresEntity: false,
  fields: [
    { name: 'width', type: 'number', label: 'Width', default: 700, min: 400, category: 'layout' },
    { name: 'height', type: 'number', label: 'Height', default: 260, min: 180, category: 'layout' },
    { name: 'layout', type: 'select', label: 'Layout', default: 'default', category: 'behavior', options: [
      { value: 'default', label: 'QWERTY' },
      { value: 'numeric', label: 'Numeric Pad' },
    ]},
    { name: 'target_entity', type: 'entity', label: 'Target Entity (input_text)', default: '', category: 'behavior' },
    { name: 'showDisplay', type: 'checkbox', label: 'Show Input Display', default: true, category: 'behavior' },
    { name: 'backgroundColor', type: 'color', label: 'Background Color', default: '#1e1e1e', category: 'style' },
    { name: 'buttonColor', type: 'color', label: 'Button Color', default: '#3b3b3b', category: 'style' },
    { name: 'buttonTextColor', type: 'color', label: 'Button Text Color', default: '#ffffff', category: 'style' },
    { name: 'buttonHoverColor', type: 'color', label: 'Button Hover Color', default: '#5a5a5a', category: 'style' },
    { name: 'displayBackgroundColor', type: 'color', label: 'Display Background', default: '#2a2a2a', category: 'style' },
    { name: 'displayTextColor', type: 'color', label: 'Display Text Color', default: '#ffffff', category: 'style' },
  ],
};

const ScreensaverWidgetMetadata: WidgetMetadata = {
  name: 'Screensaver',
  icon: 'BedtimeOutlined',
  category: 'display',
  description: 'Idle timer that shows a dim or black overlay after inactivity. Dismiss by touching or pressing a key.',
  defaultSize: { w: 160, h: 80 },
  minSize: { w: 80, h: 50 },
  requiresEntity: false,
  fields: [
    { name: 'width', type: 'number', label: 'Width', default: 160, min: 80, category: 'layout' },
    { name: 'height', type: 'number', label: 'Height', default: 80, min: 50, category: 'layout' },
    { name: 'idleTimeout', type: 'number', label: 'Idle Timeout (sec)', default: 120, min: 5, max: 3600, category: 'behavior' },
    { name: 'mode', type: 'select', label: 'Mode', default: 'dim', category: 'behavior', options: [
      { value: 'dim', label: 'Dim overlay' },
      { value: 'black', label: 'Full black' },
    ]},
    { name: 'dismissOnTouch', type: 'checkbox', label: 'Dismiss on Touch/Click', default: true, category: 'behavior' },
    { name: 'dismissOnKeyboard', type: 'checkbox', label: 'Dismiss on Keypress', default: true, category: 'behavior' },
    { name: 'dimOpacity', type: 'slider', label: 'Dim Opacity (%)', default: 85, min: 10, max: 100, step: 5, category: 'style' },
    { name: 'overlayColor', type: 'color', label: 'Overlay Color', default: '#000000', category: 'style' },
  ],
};

// Extend registry
(WIDGET_CATALOG as Record<string, WidgetMetadata>)['scrollablecontainer'] = ScrollableContainerWidgetMetadata;
(WIDGET_CATALOG as Record<string, WidgetMetadata>)['keyboard'] = KeyboardWidgetMetadata;
(WIDGET_CATALOG as Record<string, WidgetMetadata>)['screensaver'] = ScreensaverWidgetMetadata;

const LovelaceCardWidgetMetadata: WidgetMetadata = {
  name: 'Lovelace Card',
  icon: 'DashboardOutlined',
  category: 'display',
  description: 'Embed any Home Assistant Lovelace card. Only functional when loaded inside the HA frontend context.',
  defaultSize: { w: 400, h: 300 },
  fields: [
    { name: 'width',         type: 'number',   label: 'Width',            default: 400,        category: 'layout' },
    { name: 'height',        type: 'number',   label: 'Height',           default: 300,        category: 'layout' },
    { name: 'cardType',      type: 'select',   label: 'Card Type',        default: 'entities', category: 'behavior',
      options: [
        { label: 'Entities',       value: 'entities' },
        { label: 'Tile',           value: 'tile' },
        { label: 'Button',         value: 'button' },
        { label: 'Gauge',          value: 'gauge' },
        { label: 'Glance',         value: 'glance' },
        { label: 'Thermostat',     value: 'thermostat' },
        { label: 'History Graph',  value: 'history-graph' },
        { label: 'Light',          value: 'light' },
        { label: 'Media Control',  value: 'media-control' },
        { label: 'Map',            value: 'map' },
        { label: 'Markdown',       value: 'markdown' },
        { label: 'Custom…',        value: 'custom:' },
      ],
    },
    { name: 'cardConfig',      type: 'textarea', label: 'Card Config (YAML/JSON)', default: '',   category: 'behavior' },
    { name: 'refreshInterval', type: 'number',   label: 'Auto-refresh (ms, 0=off)', default: 0,  category: 'behavior',
      min: 0, step: 1000 },
  ],
};
(WIDGET_CATALOG as Record<string, WidgetMetadata>)['lovelacecard'] = LovelaceCardWidgetMetadata;
